site_name: MkDocs Placeholder Plugin
repo_url: https://github.com/six-two/mkdocs-placeholder-plugin
repo_name: mkdocs-placeholder-plugin

theme:
  name: material
  icon:
    repo: fontawesome/brands/github 
  features:
  - navigation.sections
plugins:
- placeholder:
    show_warnings: true
    static_pages:
    - "tests/static_replacements/index.html"
    replace_delay_millis: -1
    # # Uncomment for testing
    # table_default_show_readonly: True
    # table_default_type: description
- badges
- search

nav:
- index.md
- usage.md
- advanced-configuration.md
- advanced-usage.md
- demo.md
- "Tests":
  - tests/basic.md
  - tests/mermaid_diagrams.md
  - tests/static_replacements.md

markdown_extensions:
  # Message/error/warning boxes
  - admonition
  # For mermaid diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
