site_name: MkDocs Placeholder Plugin
plugins:
- placeholder:
    show_warnings: true
    static_pages:
    - "static_replacements/*.html"
- badges
- search
nav:
- index.md
- usage.md
- advanced-configuration.md
- advanced-usage.md
- demo.md
- tests.md
